version: "3"

services:
  frontend:
    image: 03farhan/ecosystem-collaboration-tool:frontend
    volumes:
      - "./frontend:/frontend"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    env_file:
      - ./backend/.env
    image: 03farhan/ecosystem-collaboration-tool:backend
    volumes:
      - "./backend:/backend"
    ports:
      - 9000:9000
    environment:
      - CHOKIDAR_USEPOLLING=true
